#:import ZBarCam kivy_garden.zbarcam.ZBarCam
BoxLayout:
    orientation: 'vertical'
    ZBarCam:
        id: zbarcam
        # optional, override the camera index (default 0)
        camera_index: 0     # or try a different value
        # optional, by default checks all types
        code_types: 'QRCODE', 'EAN13'
    Label:
        id: input
        size_hint: None, None
        size: self.texture_size[0], 50
        text: ', '.join([str(symbol.data) for symbol in zbarcam.symbols])